### ISSUE TITLE
thrown in /var/www/openvpn-admin/include/connect.php on line 5"

### ISSUE THREAD

**Issue by typ431127** [Chocobozzz/OpenVPN-Admin#105]
* **PHP version:**
7.1.0
* **MySQL version:**
5.5.56
* **Webserver (Nginx, Apache...):**
nginx
* **What is the expected behaviour?**
* **What do you see instead?**
* **PHP logs on pastebin:**
[09-May-2018 18:11:48] WARNING: [pool www] child 32483 said into stderr: "Stack trace:"
[09-May-2018 18:11:48] WARNING: [pool www] child 32483 said into stderr: "#0 /var/www/openvpn-admin/include/connect.php(5): PDO->__construct('mysql:host=loca...', 'admin', '123456', Array)"
[09-May-2018 18:11:48] WARNING: [pool www] child 32483 said into stderr: "#1 /var/www/openvpn-admin/index.php(5): require('/var/www/openvp...')"
[09-May-2018 18:11:48] WARNING: [pool www] child 32483 said into stderr: "#2 {main}"
[09-May-2018 18:11:48] WARNING: [pool www] child 32483 said into stderr: "  thrown in /var/www/openvpn-admin/include/connect.php on line 5"
[09-May-2018 18:11:49] WARNING: [pool www] child 32484 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/openvpn-admin/include/connect.php:5"
[09-May-2018 18:11:49] WARNING: [pool www] child 32484 said into stderr: "Stack trace:"
[09-May-2018 18:11:49] WARNING: [pool www] child 32484 said into stderr: "#0 /var/www/openvpn-admin/include/connect.php(5): PDO->__construct('mysql:host=loca...', 'admin', '123456', Array)"
[09-May-2018 18:11:49] WARNING: [pool www] child 32484 said into stderr: "#1 /var/www/openvpn-admin/index.php(5): require('/var/www/openvp...')"
[09-May-2018 18:11:49] WARNING: [pool www] child 32484 said into stderr: "#2 {main}"
[09-May-2018 18:11:49] WARNING: [pool www] child 32484 said into stderr: "  thrown in /var/www/openvpn-admin/include/connect.php on line 5"
[09-May-2018 18:11:50] WARNING: [pool www] child 32483 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/openvpn-admin/include/connect.php:5"
[09-May-2018 18:11:50] WARNING: [pool www] child 32483 said into stderr: "Stack trace:"
[09-May-2018 18:11:50] WARNING: [pool www] child 32483 said into stderr: "#0 /var/www/openvpn-admin/include/connect.php(5): PDO->__construct('mysql:host=loca...', 'admin', '123456', Array)"
[09-May-2018 18:11:50] WARNING: [pool www] child 32483 said into stderr: "#1 /var/www/openvpn-admin/index.php(5): require('/var/www/openvp...')"
[09-May-2018 18:11:50] WARNING: [pool www] child 32483 said into stderr: "#2 {main}"
[09-May-2018 18:11:50] WARNING: [pool www] child 32483 said into stderr: "  thrown in /var/www/openvpn-admin/include/connect.php on line 5"

**Comment by alejosv** [comment]
The logs indicate you could have some issue with you database server. You can test you database connection trying make a connection with of console. Other thing to consider is if your database credential setting on `/include/config.php` are correct.
